### ISSUE TITLE
User Story: Start as new user

### ISSUE THREAD

**Issue by teavirdis** [teavirdis/planning-meme#33]
Given I am anonymous user access main url
When I enter my name 
And I press submit button
Then I am redirected to the board list (empty for now)

**Comment by teavirdis** [comment]
hello Maksim, could you please verify.

**Comment by maximelyashevich** [comment]
Hello Aliona, I've just verified creating new user and drew conclusion: username validation works correct (there are identified not null check and regex contraint: (for example, lenght of username must be between 3 and 20 characters)).
